<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="11.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DivaModManager.Core\DivaModManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\DivaModManager\Assets\**\*">
      <Link>Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </AvaloniaResource>
  </ItemGroup>
</Project>
